# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beabad0958428ec7863cdff5d71acd3dd33cbecc6637fc096b345f583c6ea071864344fd027860c35b0e09746f61eaad218fb35429fe3c425db4e5c6b932e873

test:
  secret_key_base: c9172cf3cf72d5956f5176a2a8c6ab8d0bda71621efbe183a983bd5cc6884aa79ad38b687ef5c5598bf6230a31f63496fe45c05531c85b79cff2b5ccaa5fae80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
